### ISSUE TITLE
论文题目没有居中

### ISSUE THREAD

**Issue by DDL-IN-MY-AGENDA** [CSGrandeur/SZTU-Thesis-Latex-Template#2]
![image](https://github.com/SZTU-ACM/SZTU-Thesis-Latex-Template/assets/81623093/65580d7e-bbf6-40c6-880f-4003c1be4a96)
![image](https://github.com/SZTU-ACM/SZTU-Thesis-Latex-Template/assets/81623093/4f4ee140-f2bf-422f-a89e-5d5121de4dea)

**Comment by DDL-IN-MY-AGENDA** [comment]
\begin{center} \zihao{2}\kaishu\bfseries \@titlecn \end{center} 我用这个可以

**Comment by CSGrandeur** [comment]
可能是texlive版本问题？改天测一测。
